services:
  postgres:
    image: postgres 
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  kafka:
    image: apache/kafka:latest
    container_name: kafka
