services:
  postgres:
    image: postgres 
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d ${DB_NAME}"]
      interval: 10s
      timeout: 10s
      retries: 5
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
  web:
    container_name: ecommerce_web
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GOOSE_DRIVER: ${GOOSE_DRIVER}
      DB_NAME: ${DB_NAME}
      PGPASSWORD: ${PGPASSWORD}
      GOOSE_DBSTRING: > 
        host=postgres port=5432 user=postgres 
        password=${PGPASSWORD} dbname=${DB_NAME} sslmode=disable
      GOOSE_MIGRATION_DIR: ${GOOSE_MIGRATION_DIR}
      KAFKA_HOST: "kafka:9092"
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      GRPC_PORT: ${GRPC_PORT}
    ports:
      - "8080:8080"
